### ISSUE TITLE
Run tests across all packages when one changes

### ISSUE THREAD

**Issue by distantnative** [k-next/next#10]
At the moment we have tests in each package (well in most). However, when we change one, only those tests are run. We need a way that all tests run to see if changes in one package affect other packages which need to be changed as well.

**Comment by lukasbestle** [comment]
Hm, that shouldn't actually be required if we take the whole modular package idea seriously (at least after the first initial stable release). Each package must have a stable API to the outside. That API must only be changed in larger releases and all changes must be documented anyway.

What we will definitely need to have is a test runner for releases. Basically the release build tool we are going to write needs to run all unit tests together and also run the integration and UI tests based on that. But I don't think we should need to run all tests on every change in any package.

**Comment by distantnative** [comment]
I think we are talking pretty much about the same situation: larger changes and before releases. I did not mean on every change while coding, but for all changes that end up being released.
Cause even though the packages are more modular, they still have certain dependencies.

**Comment by lukasbestle** [comment]
Just to avoid a misunderstanding: What do you mean with "all changes that end up being released"? When should we run those tests? Right before the release or should it be possible to run those at any time?

Maybe we should just build a "test everything" feature into the build tool so that the automatic tests can be kicked off even without actually releasing anything (which shouldn't be hard if we implement the build tool anyway). Then we could "test" if a package works in the Kirby ecosystem in a dry-run.

**Comment by bastianallgeier** [comment]
I think this is exactly what Nico means. Right now if we work on a package, we can not be sure if we break anything in any other package that depends on it. But I think this will also be covered as soon as we have integration and e2e tests.

**Comment by bastianallgeier** [comment]
We really have to take "breaking changes" more serious in packages. The good thing here is that Composer gives us a more reliable way of sticking to a certain package version. We should basically treat our own packages just like any other dependency.

**Comment by lukasbestle** [comment]
Yes, I agree. But as I said, we shouldn't break anything in other packages anyway because our outside API needs to be stable. But of course I understand that we can't develop with those ideals during "move fast and break things" alpha times. ;)

So let's see how relevant this is in the long run. Of course we should keep it in mind anyway (as I said, building such a feature in isn't hard while you are at it).

> We should basically treat our own packages just like any other dependency.

Yep! 👍
